services:
  mysql:
    image: mariadb:11.4
    container_name: mysql
    command: ["--max-allowed-packet=512M"]
    volumes:
      - "./data/db:/var/lib/mysql:delegated"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    networks:
      - default
    expose:
      - "3306"
      
  litespeed:
    image: litespeedtech/openlitespeed:${OLS_VERSION}-${PHP_VERSION}
    container_name: litespeed
    env_file:
      - .env
    volumes:
      - ./lsws/conf:/usr/local/lsws/conf
      - ./lsws/admin-conf:/usr/local/lsws/admin/conf
      - ./bin/container:/usr/local/bin
      - ./sites:/var/www/vhosts/
      - ./acme:/root/.acme.sh/
      - ./logs:/usr/local/lsws/logs/
    ports:
      - "8086:80"
      - "8443:443"
      - "8443:443/udp"
      - "7080:7080"
    restart: always
    environment:
      TZ: ${TimeZone}
    networks:
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.embalabox-oficial.rule=Host(`embalabox.anthonymax.com`)"
      - "traefik.http.routers.embalabox-oficial.entrypoints=web"
      - "traefik.http.services.embalabox-oficial.loadbalancer.server.port=80"
      - "traefik.http.routers.embalabox-oficial-secure.rule=Host(`embalabox.anthonymax.com`)"
      - "traefik.http.routers.embalabox-oficial-secure.entrypoints=websecure"
      - "traefik.http.routers.embalabox-oficial-secure.tls=true"
      
  phpmyadmin:
    image: bitnami/phpmyadmin:5.2.2
    container_name: phpmyadmin
    ports:
      - "8081:8080"
      - "8444:8443"
    environment:
        DATABASE_HOST: mysql
        PMA_PORT: 8080
        PMA_PMADB: phpmyadmin
    restart: always
    networks:
      - default
    depends_on:
      - mysql
      
  redis:
    image: "redis:alpine"
    container_name: redis
    volumes:
      - ./redis/data:/var/lib/redis
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    restart: always
    networks:
      - default
    expose:
      - "6379"

  # Setup inicial usando scripts oficiais
  setup:
    image: litespeedtech/openlitespeed:${OLS_VERSION}-${PHP_VERSION}
    container_name: setup
    volumes:
      - ./lsws/conf:/usr/local/lsws/conf
      - ./sites:/var/www/vhosts/
      - ./scripts:/scripts
      - ./bin:/usr/local/bin
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}:${DB_PORT}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      DOMAIN: embalabox.anthonymax.com
    command: ["/scripts/setup-oficial.sh"]
    restart: "no"
    networks:
      - default
    depends_on:
      - litespeed
      
networks:
  default:
    driver: bridge 