services:
  litespeed:
    image: litespeedtech/openlitespeed:latest
    container_name: litespeed
    env_file:
      - .env
    volumes:
      - ./lsws/conf:/usr/local/lsws/conf
      - ./lsws/admin-conf:/usr/local/lsws/admin/conf
      - ./bin/container:/usr/local/bin
      - ./sites:/var/www/vhosts/
      - ./acme:/root/.acme.sh/
      - ./logs:/usr/local/lsws/logs/
    ports:
      - "8086:80"
      - "8443:443"
      - "8443:443/udp"
      - "7080:7080"
    restart: always
    environment:
      TZ: ${TimeZone}
    networks:
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.embalabox.rule=Host(`embalabox.example.com`)"
      - "traefik.http.routers.embalabox.entrypoints=web"
      - "traefik.http.services.embalabox.loadbalancer.server.port=80"
    depends_on:
      - wordpress-installer
      - litespeed-config
  wordpress-installer:
    image: litespeedtech/openlitespeed:latest
    container_name: wordpress-installer
    env_file:
      - .env
    volumes:
      - ./sites:/var/www/vhosts/
      - ./scripts/install-wordpress.sh:/install-wordpress.sh
    command: ["/bin/bash", "/install-wordpress.sh"]
    networks:
      - default
    restart: "no"
  litespeed-config:
    image: litespeedtech/openlitespeed:latest
    container_name: litespeed-config
    env_file:
      - .env
    volumes:
      - ./lsws/conf:/usr/local/lsws/conf
      - ./sites:/var/www/vhosts/
      - ./scripts/configure-litespeed.sh:/configure-litespeed.sh
    command: ["/bin/bash", "/configure-litespeed.sh"]
    networks:
      - default
    restart: "no"
    depends_on:
      - wordpress-installer
  phpmyadmin:
    image: bitnami/phpmyadmin:5.2.2
    ports:
      - "8081:8080"
      - "8444:8443"
    environment:
        DATABASE_HOST: ${MYSQL_HOST}
        DATABASE_PORT_NUMBER: ${MYSQL_PORT}
        DATABASE_USER: ${MYSQL_USER}
        DATABASE_PASSWORD: ${MYSQL_PASSWORD}
        PMA_PORT: 8080
    restart: always
    networks:
      - default
  redis:
    image: "redis:alpine"
    volumes:
      - ./redis/data:/var/lib/redis
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    restart: always
    networks:
      - default
    expose:
      - "6379"
networks:
  default:
    driver: bridge
